# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy all files
COPY . .

# Upgrade pip and install build dependencies
RUN pip install --upgrade pip \
    && pip install hatchling \
    && pip install .

# Expose port if necessary (if MCP server listens on a port, not clear though)

# Run the MCP server
CMD ["codemcp"]
